# docker-compose -f docker-compose-prod.yml up --build
# docker-compose -f docker-compose-prod.yml down
# docker-compose -f docker-compose-prod.yml up
services:
  bot:
    restart: always
    image: mileshkin89/ci_cd_test:compose_start
    container_name: ci_cd_test
    command: [ "python", "main.py" ]
    env_file:
      - .env
    environment:
      - LOG_LEVEL=debug
      - PYTHONPATH=/usr
    volumes:
      - logs_data:/usr/src/ci_cd_logs
    networks:
      - test_net

volumes:
  logs_data:
    driver: local

networks:
  test_net:
    driver: bridge